flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location:
    git: git@github.com:callummance/libsharlayan
    commit: 9d9d886168cfca756dd2fb0e27f7dbe2578055ce
  extra-dep: true
extra-deps:
- discord-hs-0.2.1
resolver: lts-8.5
